export const TOGGLE_POPUP_SIGNUP = 'TOGGLE_POPUP_SIGNUP';
export const TOGGLE_POPUP_LOGIN = 'TOGGLE_POPUP_LOGIN';
export const REORDER_BOOKMARKS = 'REORDER_BOOKMARKS';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';